name = "keyan-m/cardano-recorded-mint"
version = "0.1.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "A generic Cardano NFT minting script written in Aiken, with on-chain record of all mints"

[repository]
user = "keyan-m"
project = "cardano-recorded-mint"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.0.0"
source = "github"
